#!/usr/bin/env python3
"""Documentation link & file-reference auditor (release-governance tooling).

Scope: read-only. Never mutates the repository.

What it checks
--------------
1. Markdown inline links `[text](target)` in every tracked ``*.md`` file:
   - relative targets must resolve to an existing path in the repo
   - anchors (`#frag`) are stripped before resolution
   - external `http(s)://`, `mailto:` and pure-anchor links are reported but
     never fetched (this repo is audited in an egress-restricted sandbox)
2. Backtick-quoted repository paths (e.g. `` `docs/API.md` ``, `` `scripts/x.py` ``)
   that *look* like file references and do not exist. This catches stale
   documentation that names files which were renamed or never committed.

Usage
-----
    python scripts/audit_docs_links.py [--json REPORT.json] [--include-prompts]

Exit codes
----------
    0  no broken relative links and no missing referenced files
    1  at least one broken reference

Audit/governance reports (``integration-request.md``, ``docs/RELEASE_*.md``,
``docs/agent-reports/**``) are excluded from check 2 by default: they exist in
order to list paths that are missing or proposed, so auditing them would simply
re-report their own contents. Pass ``--include-reports`` to audit them anyway.

By default the historical prompt/spec files at the repository root
(``*MASTER_PROMPT*.md``, ``PHASE0_AUDIT_GUIDE.md``, ``CONTINUATION_PROMPT_V2.md``)
and ``agent-master-prompts/`` are skipped: they are point-in-time instruction
documents, not living documentation. Pass ``--include-prompts`` to audit them too.
"""
from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]

MD_LINK = re.compile(r"\[(?P<text>[^\]\n]*)\]\((?P<target>[^)\s]+)(?:\s+\"[^\"]*\")?\)")
# Backticked tokens that look like repo paths: contain a "/" or a known suffix.
BACKTICK = re.compile(r"`([^`\n]{2,120})`")
PATHISH_SUFFIX = (
    ".md", ".py", ".ts", ".tsx", ".json", ".yml", ".yaml", ".sh", ".ini",
    ".toml", ".txt", ".env", ".conf", ".mts", ".html", ".css",
)
EXTERNAL_PREFIXES = ("http://", "https://", "mailto:", "tel:", "data:")

# Source roots documentation legitimately writes paths relative to.
CANDIDATE_ROOTS = (
    "",
    "backend",
    "frontend",
    "frontend/src",
    "frontend/src/pages",
    "frontend/src/components",
    "backend/app",
    "backend/scripts",
    "docs",
)

# Paths that are intentionally NOT tracked (generated by the operator at deploy
# time). Referencing them in docs is correct, so they must not be reported.
INTENTIONALLY_UNTRACKED = {
    ".env",
    ".env.local",
    "backend/decor.sqlite3",
    "frontend/dist",
    "dist/index.html",  # generated frontend artifact cited by the performance report
    "lighthouse-report.json",
    # ---- Stage 07 additions: pre-existing dangling refs, each registered in
    # integration-request.md (IR-003 / IR-SEC-007) with its owning stage. They
    # are allowlisted so the CI docs-link gate fails only on NEW defects:
    #   docs/DATASETS_AUDIT.md:49  (owner 04) — .env.example.v2 never existed
    #   docs/reports/ACCEPTANCE_REPORT.md:13 (owner 08) — embeddings_real.json
    #     is generated on a networked machine, not committed;
    #   docs/ARCHITECTURE.md:64 uses the backend/-prefixed spelling (same file)
    #   docs/security/PRODUCTION_SECURITY_CHECKLIST.md:86 (owner 03) —
    #     /openapi.json is a runtime artifact, disabled in production
    #   docs/security/THREAT_MODEL.md:220 (owner 03) — anticipated script name;
    #     implemented as backend/scripts/prune_audit_logs.py (Stage 07)
    ".env.example.v2",
    "seed_data/embeddings_real.json",
    "backend/seed_data/embeddings_real.json",
    "/openapi.json",
    "scripts/purge_audit_logs.py",
    # ci/README.md documents the activation path: the workflow file is created
    # there by scripts/enable_ci.sh when a token with `workflows` scope pushes
    # it (the agent App token cannot — see infra-report, CI-activation).
    ".github/workflows/ci.yml",
}

# Governance/audit documents whose *purpose* is to enumerate paths that do not
# exist (dangling references, proposed files, files pending creation). Running
# the backtick file-reference check over them re-reports every finding they were
# written to report, so they are excluded from THAT check by default. Markdown
# link resolution is still enforced on them. Use --include-reports to override.
AUDIT_REPORT_FILES = {
    "integration-request.md",
    "docs/RELEASE_BASELINE.md",
    "docs/RELEASE_CHECKLIST.md",
    "docs/REPRODUCIBILITY.md",
    "docs/ROLLBACK_AND_VERSIONING.md",
    "docs/agent-reports/baseline-release-report.md",
    "docs/agent-reports/baseline-release-evidence/README.md",
    "docs/agent-reports/infra-report.md",
    "docs/agent-reports/infra-evidence/README.md",
}

SKIP_DEFAULT = {
    "ADVANCED_MASTER_PROMPT_V2.md",
    "CONTINUATION_PROMPT_V2.md",
    "MASTER_PROMPT_V3_DATASETS_INTEGRATION.md",
    "PHASE0_AUDIT_GUIDE.md",
}
SKIP_DIR_DEFAULT = {"agent-master-prompts"}


def tracked_markdown(include_prompts: bool) -> list[Path]:
    out = subprocess.run(
        ["git", "ls-files", "*.md"], cwd=REPO, capture_output=True, text=True, check=True
    ).stdout.split()
    files = []
    for rel in out:
        p = Path(rel)
        if not include_prompts:
            if p.name in SKIP_DEFAULT or (p.parts and p.parts[0] in SKIP_DIR_DEFAULT):
                continue
        files.append(p)
    return sorted(files)


def resolve(md_file: Path, target: str) -> Path:
    """Resolve a relative link the way GitHub does: relative to the file's dir,
    with a repo-root fallback for root-anchored targets."""
    if target.startswith("/"):
        return REPO / target.lstrip("/")
    return (REPO / md_file.parent / target).resolve()


def audit(include_prompts: bool, include_reports: bool = False) -> dict:
    broken_links: list[dict] = []
    external: list[dict] = []
    missing_refs: list[dict] = []
    checked_links = 0
    checked_refs = 0

    for md in tracked_markdown(include_prompts):
        text = (REPO / md).read_text(encoding="utf-8", errors="replace")
        for lineno, line in enumerate(text.splitlines(), start=1):
            for m in MD_LINK.finditer(line):
                target = m.group("target").strip()
                if target.startswith(EXTERNAL_PREFIXES):
                    external.append({"file": str(md), "line": lineno, "target": target})
                    continue
                if target.startswith("#"):
                    continue
                checked_links += 1
                path_part = target.split("#", 1)[0]
                if not path_part:
                    continue
                if not resolve(md, path_part).exists():
                    broken_links.append(
                        {"file": str(md), "line": lineno, "target": target,
                         "text": m.group("text")}
                    )
            if str(md) in AUDIT_REPORT_FILES and not include_reports:
                continue
            for m in BACKTICK.finditer(line):
                token = m.group(1).strip()
                if " " in token or token.startswith(EXTERNAL_PREFIXES):
                    continue
                if any(ch in token for ch in "[]*?<>|…"):
                    continue  # glob / elided / placeholder notation, not a real path
                if token.startswith(".") and "/" not in token and token.count(".") == 1:
                    continue  # a bare file extension such as `.json`, not a path
                looks_pathish = (
                    token.endswith(PATHISH_SUFFIX) and ("/" in token or token.startswith("."))
                ) or token.startswith(".env")
                if not looks_pathish:
                    continue
                checked_refs += 1
                if token in INTENTIONALLY_UNTRACKED:
                    continue
                cand = [REPO / md.parent / token]
                cand += [REPO / root / token for root in CANDIDATE_ROOTS]
                if not any(c.exists() for c in cand):
                    missing_refs.append({"file": str(md), "line": lineno, "ref": token})

    return {
        "markdown_files_audited": len(tracked_markdown(include_prompts)),
        "audit_reports_excluded_from_ref_check": (
            [] if include_reports else sorted(AUDIT_REPORT_FILES)
        ),
        "relative_links_checked": checked_links,
        "backtick_path_refs_checked": checked_refs,
        "external_links_found_not_fetched": len(external),
        "broken_relative_links": broken_links,
        "missing_backtick_path_refs": missing_refs,
        "external_links": external,
    }


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--json", dest="json_out", help="write a JSON report to this path")
    ap.add_argument("--include-prompts", action="store_true",
                    help="also audit historical master-prompt/spec documents")
    ap.add_argument("--include-reports", action="store_true",
                    help="also run the file-reference check over audit/governance "
                         "reports (they intentionally cite paths that do not exist)")
    args = ap.parse_args()

    report = audit(args.include_prompts, args.include_reports)

    print("=== DOCS LINK AUDIT ===")
    print(f"markdown files audited     : {report['markdown_files_audited']}")
    print(f"relative links checked     : {report['relative_links_checked']}")
    print(f"backtick path refs checked : {report['backtick_path_refs_checked']}")
    print(f"external links (not fetched): {report['external_links_found_not_fetched']}")
    if report["audit_reports_excluded_from_ref_check"]:
        print(f"audit reports excluded from the file-reference check: "
              f"{len(report['audit_reports_excluded_from_ref_check'])} "
              f"(use --include-reports to audit them too)")
    print()

    if report["broken_relative_links"]:
        print(f"[BROKEN LINKS] {len(report['broken_relative_links'])}")
        for b in report["broken_relative_links"]:
            print(f"  {b['file']}:{b['line']} -> {b['target']}")
    else:
        print("[BROKEN LINKS] 0")
    print()

    if report["missing_backtick_path_refs"]:
        print(f"[MISSING FILE REFERENCES] {len(report['missing_backtick_path_refs'])}")
        for b in report["missing_backtick_path_refs"]:
            print(f"  {b['file']}:{b['line']} -> {b['ref']}")
    else:
        print("[MISSING FILE REFERENCES] 0")

    failed = bool(report["broken_relative_links"]) or bool(report["missing_backtick_path_refs"])
    print()
    print("RESULT:", "FAIL" if failed else "PASS")

    if args.json_out:
        out = Path(args.json_out)
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(json.dumps(report, indent=2, ensure_ascii=False), encoding="utf-8")
        print(f"report : {out}")

    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main())
